apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-${VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: capstone-app
        version: ${VERSION}
    spec:
      containers:
      - name: capstone-app
        image: thiennnt/capstone_devops:${VERSION}
        ports:
        - containerPort: 80
