apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: capstone-app
        version: 1.0.0
    spec:
      containers:
      - name: capstone-app
        image: thiennnt/capstone_devops:1.0.0
        ports:
        - containerPort: 80
