apiVersion: v1
kind: Service
metadata:
  name: capstone_app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: capstone_app
    version: 1.0.0
  type: LoadBalancer